### ISSUE TITLE
UNIVERSAL->import is deprecated and will be removed in a future perl at cxgn-corelibs/lib/CXGN/Tools/Run.pm line 17.

### ISSUE THREAD

**Issue by jeremyde** [solgenomics/cxgn-corelibs#7]
UNIVERSAL::isa is deprecated.  Do something like this instead:

if (eval { $obj->isa($class) }) {

**Comment by isaak** [comment]
Done for cxgn tools run: https://github.com/solgenomics/cxgn-corelibs/commit/0d564ec325ec333ac5c651a383669d221bd4e45d
